version: '3.5'

services:

    portal-db:
        image: postgres:9.6-alpine
        container_name: portal-db
        environment:
            POSTGRES_USER: do_portal
            POSTGRES_PASSWORD: do_portal
            POSTGRES_DB: do_portal
        volumes:
            - portal_db_data:/var/lib/postgresql/data
    portal-backend:
        container_name: portal-backend
        build: ./backend
        ports:
            - "5001:5001"

    portal-frontend:
        container_name: portal-frontend
        build: ./frontend
        ports:
            - "5002:5002"
            - "35729:35729"

    epplication_db:
        image: postgres:9.6-alpine
        container_name: epplication_db
        environment:
            POSTGRES_USER: epplication
            POSTGRES_PASSWORD: epplication
            POSTGRES_DB: epplication
        volumes:
            - epplication_db_data:/var/lib/postgresql/data
    selenium:
        image: selenium/standalone-firefox-debug
        container_name: epplication_selenium
        volumes:
            - /dev/shm:/dev/shm
        ports:
            - "5900:5900"
    app:
        container_name: epplication_app
        image: davewood/epplication:latest
        depends_on:
            - epplication_db
        volumes:
            - app_data_job_exports:/home/epplication/EPPlication/root/job_exports
            - app_data_ssh_keys:/home/epplication/EPPlication/ssh_keys
        ports:
            - "8080:80"

volumes:
    portal_db_data:
    epplication_db_data:
    app_data_job_exports:
    app_data_ssh_keys:
